version: '3.7'

services:
  iot-mongo:
    image: mongo:latest
    container_name: iot-mongo
    restart: always
    ports:
      - 24400:27017

    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./config/mongod.conf:/etc/mongod.conf
      - ./data/:/data/db/
      - ./log/:/var/log/mongodb/

    command: ["-f", "/etc/mongod.conf"]

  iot-mongo-express:
    image: mongo-express
    container_name: iot-mongo-express
    ports:
      - 24401:8081
    volumes:
      - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: iot-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - iot-mongo